# Generated by Django 3.0 on 2019-12-11 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50)),
                ('pgn', models.TextField()),
                ('timeClass', models.CharField(max_length=30)),
                ('rules', models.CharField(max_length=30)),
                ('whiteResult', models.CharField(max_length=25)),
                ('blackResult', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('winPercentage', models.IntegerField()),
                ('lossPercentage', models.IntegerField()),
                ('drawPercentage', models.IntegerField()),
                ('whiteWinPercentage', models.IntegerField()),
                ('blackWinPercentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blackPlayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Black', to='statsboard.Player')),
                ('gameUrl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statsboard.Game')),
                ('whitePlayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='White', to='statsboard.Player')),
            ],
        ),
    ]
