# Generated by Django 3.0 on 2019-12-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergames',
            name='gameNum',
            field=models.CharField(default='25', max_length=50),
        ),
    ]
